version: '3.4'

services:
  varnish:
    container_name: varnish
    build: ./..
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=80
      - ACL_PURGE_HOST=localhost
      - TZ=Europe/Warsaw
    networks:
      - base

  backend:
    container_name: backend
    image: nginx
    networks:
      - base

networks:
  base: